# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# BluGen, 2014
# Fabian <vondor666@gmail.com>, 2014
# Michael Tremer <michael.tremer@ipfire.org>, 2012,2014
# Peter Cloudstone <rmg-mainz@web.de>, 2014
# Sun Tiger, 2015
# BlockMall, 2014
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-05-07 12:54+0100\n"
"PO-Revision-Date: 2015-05-07 17:00+0000\n"
"Last-Translator: Sun Tiger\n"
"Language-Team: German (http://www.transifex.com/mstremer/ipfire/language/"
"de/)\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../src/ddns/__init__.py:63
msgid "Debugging mode enabled"
msgstr "Debugmodus eingeschaltet"

#: ../src/ddns/__init__.py:90
#, python-format
msgid "Loading configuration file %s"
msgstr "Lade Konfigurationsdatei %s"

#: ../src/ddns/__init__.py:156
msgid "Found no entries in the configuration file. Exiting."
msgstr "Keine Einträge in der Konfigurationsdatei gefunden. Ende."

#: ../src/ddns/__init__.py:167
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr "Dynamic DNS-Update für %(hostname)s (%(provider)s) fehlgeschlagen"

#: ../src/ddns/__init__.py:174
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr ""
"Dynamic DNS-Update für %(hostname)s (%(provider)s) erzeugte einen "
"unerwarteten Fehler:"

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr "Fehler"

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr "Netzwerkfehler"

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr ""
"Der Server hat die Anfrage aufgrund eines Missbrauchsverdachts zurückgewiesen"

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr "Die Authentifizierung am Server ist fehlgeschlagen"

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr "Der Server weist alle Aktualisierungen dieses Clients zurück"

#: ../src/ddns/errors.py:71
msgid "Invalid certificate"
msgstr ""

#: ../src/ddns/errors.py:79
msgid "The configuration file has errors"
msgstr "Die Konfigurationsdatei weist Fehler auf"

#: ../src/ddns/errors.py:86
msgid "Connection refused"
msgstr "Verbindung zurückgewiesen"

#: ../src/ddns/errors.py:93 ../src/ddns/system.py:240
msgid "Connection timeout"
msgstr "Zeitüberschreitung bei der Verbindung"

#: ../src/ddns/errors.py:101
msgid "The host could not be found in the configuration file"
msgstr "Der Host konnte in der Konfigurationsdatei nicht gefunden werden"

#: ../src/ddns/errors.py:109
msgid "Internal server error"
msgstr "Interner Serverfehler"

#: ../src/ddns/errors.py:116
msgid "Network unreachable"
msgstr "Netzwerk nicht erreichbar"

#: ../src/ddns/errors.py:123
msgid "No route to host"
msgstr ""

#: ../src/ddns/errors.py:130
msgid "Not found"
msgstr "Nicht gefunden"

#: ../src/ddns/errors.py:138
msgid "Request error"
msgstr "Request-Fehler"

#: ../src/ddns/errors.py:146
msgid "Could not resolve DNS entry"
msgstr "DNS Eintrag konnte nicht aufgelöst werden"

#: ../src/ddns/errors.py:154
msgid "SSL negotiation error"
msgstr ""

#: ../src/ddns/errors.py:161
msgid "Service unavailable"
msgstr "Dienst nicht verfügbar"

#: ../src/ddns/errors.py:169
msgid "The update could not be performed"
msgstr "Die Aktualisierung konnte nicht ausgeführt werden"

#: ../src/ddns/providers.py:85
msgid "Provider is not properly configured"
msgstr "Der Anbieter ist nicht richtig konfiguriert"

#: ../src/ddns/providers.py:154
#, python-format
msgid "Updating %s forced"
msgstr "Aktualisierung von %s erzwungen"

#: ../src/ddns/providers.py:179
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr "Dynamic DNS-Update für %(hostname)s (%(provider)s) erfolgreich"

#: ../src/ddns/providers.py:203
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because of an IP "
"address change"
msgstr ""
"Eine Aktualisierung für %(hostname)s (%(provider)s) wird aufgrund einer IP-"
"Adress Änderung vorgenommen"

#: ../src/ddns/providers.py:211
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because the holdoff "
"time has expired"
msgstr ""
"Eine Aktualisierung für %(hostname)s (%(provider)s) wird vorgenommen da die "
"Vorhaltezeit abgelaufen ist"

#. Otherwise, we don't need to perform an update
#: ../src/ddns/providers.py:218
#, python-format
msgid "No update required for %(hostname)s (%(provider)s)"
msgstr "Keine Aktualisierung für %(hostname)s (%(provider)s) erforderlich"

#: ../src/ddns/providers.py:237 ../src/ddns/providers.py:251
#, python-format
msgid "An update has not been performed because earlier updates failed for %s"
msgstr ""
"Aktualisierung wurde nicht durchgeführt, da frühere Aktualisierungen für %s "
"fehlschlugen."

#: ../src/ddns/providers.py:239
msgid "There will be no retries"
msgstr "Es werden keine weiteren Versuche durchgeführt"

#: ../src/ddns/providers.py:255
msgid "Last failure message:"
msgstr "Letzte Fehlermeldung:"

#: ../src/ddns/providers.py:260
#, python-format
msgid "Further updates will be withheld until %s"
msgstr "Weitere Aktualisierungen werden zurückgehalten bis %s"

#: ../src/ddns/providers.py:394 ../src/ddns/providers.py:668
#: ../src/ddns/providers.py:752 ../src/ddns/providers.py:1419
#: ../src/ddns/providers.py:1589
#, fuzzy
msgid "No valid FQDN was given"
msgstr "Kein gültiger FQDN angegeben."

#: ../src/ddns/providers.py:396 ../src/ddns/providers.py:670
#: ../src/ddns/providers.py:1636
#, fuzzy
msgid "Specified host does not exist"
msgstr "Der angebene Host existiert nicht."

#: ../src/ddns/providers.py:400 ../src/ddns/providers.py:674
#, fuzzy
msgid "DNS error encountered"
msgstr "DNS-Fehler aufgetreten."

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:405 ../src/ddns/providers.py:586
#: ../src/ddns/providers.py:973 ../src/ddns/providers.py:1642
#, python-format
msgid "Server response: %s"
msgstr "Antwort des Servers: %s"

#: ../src/ddns/providers.py:540
msgid "Scriptlet:"
msgstr "Scriptlet:"

#: ../src/ddns/providers.py:577
msgid "Domain not found."
msgstr "Domain nicht gefunden."

#: ../src/ddns/providers.py:676
#, fuzzy
msgid "Account disabled or locked"
msgstr "Der Account wurde deaktiviert."

#: ../src/ddns/providers.py:754 ../src/ddns/providers.py:801
#: ../src/ddns/providers.py:1682
msgid "Invalid hostname specified"
msgstr "Ungültiger Computername angegeben."

#: ../src/ddns/providers.py:756
#, fuzzy
msgid "Hostname not marked as a dynamic host"
msgstr "Computername nicht als dynamischer Computer markiert."

#: ../src/ddns/providers.py:758 ../src/ddns/providers.py:810
#: ../src/ddns/providers.py:1093
#, fuzzy
msgid "Invalid IP address has been sent"
msgstr "Ungültige IP-Adresse abgeschickt."

#: ../src/ddns/providers.py:798
#, fuzzy
msgid "No hostname specified"
msgstr "Kein Hostname angegeben."

#: ../src/ddns/providers.py:807
#, fuzzy
msgid "Account has been disabled"
msgstr "Der Account wurde deaktiviert."

#: ../src/ddns/providers.py:813
#, fuzzy
msgid "Too many failed requests"
msgstr "Zu viele fehlgeschlagene Anfragen."

#: ../src/ddns/providers.py:908
msgid "Dynamic DNS is not turned on for this domain"
msgstr ""

#: ../src/ddns/providers.py:911
#, fuzzy
msgid "Invalid data has been sent"
msgstr "Ungültige IP-Adresse abgeschickt."

#: ../src/ddns/providers.py:914 ../src/ddns/providers.py:968
#: ../src/ddns/providers.py:1591
#, fuzzy
msgid "Too frequent update requests have been sent"
msgstr "Zu häufige Aktualisierungen gesendet."

#: ../src/ddns/providers.py:964
#, fuzzy
msgid "Malformed request has been sent"
msgstr "Fehlerhafte Anfrage gesendet."

#: ../src/ddns/providers.py:1014 ../src/ddns/providers.py:1241
#, fuzzy
msgid "Domain not found"
msgstr "Domain nicht gefunden."

#: ../src/ddns/providers.py:1049
msgid "An invalid IP address was submitted"
msgstr "Eine ungültige IP Adresse wurde übermittelt"

#: ../src/ddns/providers.py:1243
#, fuzzy
msgid "Domain not active"
msgstr "Domain nicht aktiv."

#: ../src/ddns/providers.py:1393
#, fuzzy
msgid "No Auth details specified"
msgstr "Keine Authentifizierungsdetails angegeben."

#: ../src/ddns/providers.py:1415
#, fuzzy
msgid "Invalid IPv4 address has been sent"
msgstr "Eine ungültige IPv4-Adresse wurde gesendet."

#: ../src/ddns/providers.py:1417
#, fuzzy
msgid "Invalid IPv6 address has been sent"
msgstr "Eine ungültige IPv6-Adresse wurde gesendet."

#: ../src/ddns/providers.py:1630
#, fuzzy
msgid "Account has been suspended"
msgstr "Der Account wurde deaktiviert."

#: ../src/ddns/providers.py:1633
#, fuzzy
msgid "Account has been revoked"
msgstr "Der Account wurde deaktiviert."

#: ../src/ddns/system.py:56
#, python-format
msgid "Running on distribution: %s"
msgstr "Laufe auf Distribution: %s"

#: ../src/ddns/system.py:161
msgid "Request header:"
msgstr "Request-Header:"

#. Log response header.
#: ../src/ddns/system.py:169 ../src/ddns/system.py:178
#, python-format
msgid "Response header (Status Code %s):"
msgstr "Header der Antwort (Status Code %s):"

#: ../src/ddns/system.py:298
msgid "Falling back to check the IP address with help of a public server"
msgstr ""

#~ msgid "Invalid hostname specified."
#~ msgstr "Ungültiger Computername angegeben."
