# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# irenee Munyaneza <muirenee@yahoo.fr>, 2014
# nonux <nonux@free.fr>, 2015
# RafaelK <rafael@keramid.as>, 2012
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-05-07 12:54+0100\n"
"PO-Revision-Date: 2015-02-17 23:21+0000\n"
"Last-Translator: nonux <nonux@free.fr>\n"
"Language-Team: French (http://www.transifex.com/projects/p/ipfire/language/"
"fr/)\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: ../src/ddns/__init__.py:63
msgid "Debugging mode enabled"
msgstr "Mode débogage activé"

#: ../src/ddns/__init__.py:90
#, python-format
msgid "Loading configuration file %s"
msgstr "Chargement du fichier de configuration %s"

#: ../src/ddns/__init__.py:156
msgid "Found no entries in the configuration file. Exiting."
msgstr "Aucune entrée trouvée dans le fichier de configuration. Sortie."

#: ../src/ddns/__init__.py:167
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr ""
"Mise à jour du DNS dynamique pour %(hostname)s (%(provider)s) a échouée :"

#: ../src/ddns/__init__.py:174
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr ""
"Mise à jour du DNS dynamique pour %(hostname)s (%(provider)s) a retourné une "
"exception non gérée :"

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr "Erreur"

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr "Erreur du Réseau"

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr ""

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr "L'authentification avec le serveur a échoué"

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr ""

#: ../src/ddns/errors.py:71
msgid "Invalid certificate"
msgstr ""

#: ../src/ddns/errors.py:79
msgid "The configuration file has errors"
msgstr "Le fichier de configuration a des erreurs"

#: ../src/ddns/errors.py:86
msgid "Connection refused"
msgstr "Connexion refusée"

#: ../src/ddns/errors.py:93 ../src/ddns/system.py:240
msgid "Connection timeout"
msgstr "Délai de connexion"

#: ../src/ddns/errors.py:101
msgid "The host could not be found in the configuration file"
msgstr "L'hôte est introuvable dans le fichier de configuration"

#: ../src/ddns/errors.py:109
msgid "Internal server error"
msgstr "Erreur interne du serveur"

#: ../src/ddns/errors.py:116
msgid "Network unreachable"
msgstr "Réseau injoignable"

#: ../src/ddns/errors.py:123
msgid "No route to host"
msgstr ""

#: ../src/ddns/errors.py:130
msgid "Not found"
msgstr "Non trouvé"

#: ../src/ddns/errors.py:138
msgid "Request error"
msgstr ""

#: ../src/ddns/errors.py:146
msgid "Could not resolve DNS entry"
msgstr "Impossible de résoudre l'entrée DNS"

#: ../src/ddns/errors.py:154
msgid "SSL negotiation error"
msgstr ""

#: ../src/ddns/errors.py:161
msgid "Service unavailable"
msgstr "Service indisponible"

#: ../src/ddns/errors.py:169
msgid "The update could not be performed"
msgstr "La mise à jour ne peut être réalisée"

#: ../src/ddns/providers.py:85
msgid "Provider is not properly configured"
msgstr ""

#: ../src/ddns/providers.py:154
#, python-format
msgid "Updating %s forced"
msgstr ""

#: ../src/ddns/providers.py:179
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr ""
"Mise à jour du DNS dynamique pour %(hostname)s (%(provider)s) a été "
"effectuée avec succès"

#: ../src/ddns/providers.py:203
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because of an IP "
"address change"
msgstr ""

#: ../src/ddns/providers.py:211
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because the holdoff "
"time has expired"
msgstr ""

#. Otherwise, we don't need to perform an update
#: ../src/ddns/providers.py:218
#, python-format
msgid "No update required for %(hostname)s (%(provider)s)"
msgstr ""

#: ../src/ddns/providers.py:237 ../src/ddns/providers.py:251
#, python-format
msgid "An update has not been performed because earlier updates failed for %s"
msgstr ""

#: ../src/ddns/providers.py:239
msgid "There will be no retries"
msgstr ""

#: ../src/ddns/providers.py:255
msgid "Last failure message:"
msgstr "Dernier message d'erreur :"

#: ../src/ddns/providers.py:260
#, python-format
msgid "Further updates will be withheld until %s"
msgstr ""

#: ../src/ddns/providers.py:394 ../src/ddns/providers.py:668
#: ../src/ddns/providers.py:752 ../src/ddns/providers.py:1419
#: ../src/ddns/providers.py:1589
msgid "No valid FQDN was given"
msgstr ""

#: ../src/ddns/providers.py:396 ../src/ddns/providers.py:670
#: ../src/ddns/providers.py:1636
msgid "Specified host does not exist"
msgstr ""

#: ../src/ddns/providers.py:400 ../src/ddns/providers.py:674
msgid "DNS error encountered"
msgstr ""

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:405 ../src/ddns/providers.py:586
#: ../src/ddns/providers.py:973 ../src/ddns/providers.py:1642
#, python-format
msgid "Server response: %s"
msgstr ""

#: ../src/ddns/providers.py:540
msgid "Scriptlet:"
msgstr ""

#: ../src/ddns/providers.py:577
msgid "Domain not found."
msgstr "Domaine non trouvé."

#: ../src/ddns/providers.py:676
msgid "Account disabled or locked"
msgstr ""

#: ../src/ddns/providers.py:754 ../src/ddns/providers.py:801
#: ../src/ddns/providers.py:1682
msgid "Invalid hostname specified"
msgstr "Le nom d'hôte spécifié est invalide"

#: ../src/ddns/providers.py:756
msgid "Hostname not marked as a dynamic host"
msgstr ""

#: ../src/ddns/providers.py:758 ../src/ddns/providers.py:810
#: ../src/ddns/providers.py:1093
msgid "Invalid IP address has been sent"
msgstr ""

#: ../src/ddns/providers.py:798
#, fuzzy
msgid "No hostname specified"
msgstr "Pas de nom de machine spécifié."

#: ../src/ddns/providers.py:807
msgid "Account has been disabled"
msgstr ""

#: ../src/ddns/providers.py:813
msgid "Too many failed requests"
msgstr ""

#: ../src/ddns/providers.py:908
msgid "Dynamic DNS is not turned on for this domain"
msgstr ""

#: ../src/ddns/providers.py:911
msgid "Invalid data has been sent"
msgstr ""

#: ../src/ddns/providers.py:914 ../src/ddns/providers.py:968
#: ../src/ddns/providers.py:1591
msgid "Too frequent update requests have been sent"
msgstr ""

#: ../src/ddns/providers.py:964
msgid "Malformed request has been sent"
msgstr ""

#: ../src/ddns/providers.py:1014 ../src/ddns/providers.py:1241
#, fuzzy
msgid "Domain not found"
msgstr "Domaine non trouvé."

#: ../src/ddns/providers.py:1049
msgid "An invalid IP address was submitted"
msgstr ""

#: ../src/ddns/providers.py:1243
#, fuzzy
msgid "Domain not active"
msgstr "Le domaine n'est pas actif."

#: ../src/ddns/providers.py:1393
#, fuzzy
msgid "No Auth details specified"
msgstr "Pas de nom de machine spécifié."

#: ../src/ddns/providers.py:1415
msgid "Invalid IPv4 address has been sent"
msgstr ""

#: ../src/ddns/providers.py:1417
msgid "Invalid IPv6 address has been sent"
msgstr ""

#: ../src/ddns/providers.py:1630
msgid "Account has been suspended"
msgstr ""

#: ../src/ddns/providers.py:1633
msgid "Account has been revoked"
msgstr ""

#: ../src/ddns/system.py:56
#, python-format
msgid "Running on distribution: %s"
msgstr ""

#: ../src/ddns/system.py:161
msgid "Request header:"
msgstr "En-tête de requête:"

#. Log response header.
#: ../src/ddns/system.py:169 ../src/ddns/system.py:178
#, python-format
msgid "Response header (Status Code %s):"
msgstr ""

#: ../src/ddns/system.py:298
msgid "Falling back to check the IP address with help of a public server"
msgstr ""

#~ msgid "Invalid hostname specified."
#~ msgstr "Le nom de domaine spécifié est invalide."
