# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# gtufano <gt@iltofa.com>, 2014
# luX <lucianocataldo@gmail.com>, 2014
# Mario <mc9085@mclink.it>, 2014
# n.patriarchi <niccolo@cyber.it>, 2014
# umberto <web.af@email.it>, 2013
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-05-07 12:54+0100\n"
"PO-Revision-Date: 2014-09-30 13:34+0000\n"
"Last-Translator: Mario <mc9085@mclink.it>\n"
"Language-Team: Italian (http://www.transifex.com/projects/p/ipfire/language/"
"it/)\n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../src/ddns/__init__.py:63
msgid "Debugging mode enabled"
msgstr "Modalità di debug abilitata"

#: ../src/ddns/__init__.py:90
#, python-format
msgid "Loading configuration file %s"
msgstr "Carico il file di configurazione %s"

#: ../src/ddns/__init__.py:156
msgid "Found no entries in the configuration file. Exiting."
msgstr "Non ha trovato voci nel file di configurazione"

#: ../src/ddns/__init__.py:167
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr "Aggiornamento DNS dinamico fallita per  %(hostname)s (%(provider)s)"

#: ../src/ddns/__init__.py:174
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr ""
"Aggiornamento DNS dinamico per  %(hostname)s (%(provider)s) generata "
"un'eccezione non gestita:"

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr "Errore"

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr "Errore di rete"

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr ""
"Il server non processerà la richiesta perché sospetta un abuso dell'account "
"utente"

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr "L'autenticazione sul server è fallita."

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr "Il server non vuole aggiornamenti da questo client"

#: ../src/ddns/errors.py:71
msgid "Invalid certificate"
msgstr ""

#: ../src/ddns/errors.py:79
msgid "The configuration file has errors"
msgstr "Il file di configurazione ha errori"

#: ../src/ddns/errors.py:86
msgid "Connection refused"
msgstr "Connessione rifiutata"

#: ../src/ddns/errors.py:93 ../src/ddns/system.py:240
msgid "Connection timeout"
msgstr "Connessione scaduta"

#: ../src/ddns/errors.py:101
msgid "The host could not be found in the configuration file"
msgstr "L'host non può essere trovato nel file di configurazione"

#: ../src/ddns/errors.py:109
msgid "Internal server error"
msgstr "Errore interno del server"

#: ../src/ddns/errors.py:116
msgid "Network unreachable"
msgstr "Rete irraggiungibile"

#: ../src/ddns/errors.py:123
msgid "No route to host"
msgstr ""

#: ../src/ddns/errors.py:130
msgid "Not found"
msgstr "Non trovato"

#: ../src/ddns/errors.py:138
msgid "Request error"
msgstr "Errore nella richiesta"

#: ../src/ddns/errors.py:146
msgid "Could not resolve DNS entry"
msgstr "Non posso risolvere il DNS immesso"

#: ../src/ddns/errors.py:154
msgid "SSL negotiation error"
msgstr ""

#: ../src/ddns/errors.py:161
msgid "Service unavailable"
msgstr "Serivizio non disponibile"

#: ../src/ddns/errors.py:169
msgid "The update could not be performed"
msgstr "L'aggiornamento non può essere eseguito"

#: ../src/ddns/providers.py:85
msgid "Provider is not properly configured"
msgstr "Il Provider non è configurato correttamente"

#: ../src/ddns/providers.py:154
#, python-format
msgid "Updating %s forced"
msgstr "L'aggiornamento %s è stato forzato"

#: ../src/ddns/providers.py:179
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr ""
"Aggiornamento DNS dinamico per %(hostname)s (%(provider)s) eseguito con "
"successo"

#: ../src/ddns/providers.py:203
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because of an IP "
"address change"
msgstr ""
"E' in corso un'aggiornamento di %(hostname)s su (%(provider)s) poiché è "
"variato l'indirzzo IP"

#: ../src/ddns/providers.py:211
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because the holdoff "
"time has expired"
msgstr ""
"E' in corso un'aggiornamento di %(hostname)s su (%(provider)s) poiché è "
"scaduto il tempo di attesa"

#. Otherwise, we don't need to perform an update
#: ../src/ddns/providers.py:218
#, python-format
msgid "No update required for %(hostname)s (%(provider)s)"
msgstr ""
"Non è necessario nessun aggiornamento di %(hostname)s su (%(provider)s)"

#: ../src/ddns/providers.py:237 ../src/ddns/providers.py:251
#, python-format
msgid "An update has not been performed because earlier updates failed for %s"
msgstr ""
"Non è stato eseguito l'aggiornamento perché è fallito precedentemente su %s"

#: ../src/ddns/providers.py:239
msgid "There will be no retries"
msgstr "Non ci saranno nuovi tentativi"

#: ../src/ddns/providers.py:255
msgid "Last failure message:"
msgstr "Ultimo messaggio di errore"

#: ../src/ddns/providers.py:260
#, python-format
msgid "Further updates will be withheld until %s"
msgstr "Non saranno eseguiti ulteriori aggiornamenti sino a %s"

#: ../src/ddns/providers.py:394 ../src/ddns/providers.py:668
#: ../src/ddns/providers.py:752 ../src/ddns/providers.py:1419
#: ../src/ddns/providers.py:1589
#, fuzzy
msgid "No valid FQDN was given"
msgstr "Non è stato dato un valido FQDN."

#: ../src/ddns/providers.py:396 ../src/ddns/providers.py:670
#: ../src/ddns/providers.py:1636
#, fuzzy
msgid "Specified host does not exist"
msgstr "L'host specificato non esiste"

#: ../src/ddns/providers.py:400 ../src/ddns/providers.py:674
#, fuzzy
msgid "DNS error encountered"
msgstr "Errore nel DNS."

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:405 ../src/ddns/providers.py:586
#: ../src/ddns/providers.py:973 ../src/ddns/providers.py:1642
#, python-format
msgid "Server response: %s"
msgstr "Risposta del server: %s"

#: ../src/ddns/providers.py:540
msgid "Scriptlet:"
msgstr "Scriptlet:"

#: ../src/ddns/providers.py:577
msgid "Domain not found."
msgstr "Dominio non trovato."

#: ../src/ddns/providers.py:676
#, fuzzy
msgid "Account disabled or locked"
msgstr "L'utente è stato disabilitato"

#: ../src/ddns/providers.py:754 ../src/ddns/providers.py:801
#: ../src/ddns/providers.py:1682
msgid "Invalid hostname specified"
msgstr "E' stato specificato un nome host non valido"

#: ../src/ddns/providers.py:756
#, fuzzy
msgid "Hostname not marked as a dynamic host"
msgstr "Il nome host non è marcato come uno dinamico."

#: ../src/ddns/providers.py:758 ../src/ddns/providers.py:810
#: ../src/ddns/providers.py:1093
#, fuzzy
msgid "Invalid IP address has been sent"
msgstr "E' stato inviato un indirizzo IP non valido."

#: ../src/ddns/providers.py:798
#, fuzzy
msgid "No hostname specified"
msgstr "Nome dell'host non specificato"

#: ../src/ddns/providers.py:807
#, fuzzy
msgid "Account has been disabled"
msgstr "L'utente è stato disabilitato"

#: ../src/ddns/providers.py:813
#, fuzzy
msgid "Too many failed requests"
msgstr "Troppe richieste fallite"

#: ../src/ddns/providers.py:908
msgid "Dynamic DNS is not turned on for this domain"
msgstr ""

#: ../src/ddns/providers.py:911
#, fuzzy
msgid "Invalid data has been sent"
msgstr "E' stato inviato un indirizzo IP non valido."

#: ../src/ddns/providers.py:914 ../src/ddns/providers.py:968
#: ../src/ddns/providers.py:1591
#, fuzzy
msgid "Too frequent update requests have been sent"
msgstr "Sono state inviate troppe richieste di aggiornamento."

#: ../src/ddns/providers.py:964
#, fuzzy
msgid "Malformed request has been sent"
msgstr "E' stata inviata una richiesta malformata."

#: ../src/ddns/providers.py:1014 ../src/ddns/providers.py:1241
#, fuzzy
msgid "Domain not found"
msgstr "Dominio non trovato."

#: ../src/ddns/providers.py:1049
msgid "An invalid IP address was submitted"
msgstr "E' stato inserito un indirizzo IP non valido"

#: ../src/ddns/providers.py:1243
#, fuzzy
msgid "Domain not active"
msgstr "Dominio non attivo."

#: ../src/ddns/providers.py:1393
#, fuzzy
msgid "No Auth details specified"
msgstr "Nessun dettagli di autorizzazione specificato."

#: ../src/ddns/providers.py:1415
#, fuzzy
msgid "Invalid IPv4 address has been sent"
msgstr "È stato spedito un indirizzo IPv4 non valido."

#: ../src/ddns/providers.py:1417
#, fuzzy
msgid "Invalid IPv6 address has been sent"
msgstr "È stato spedito un indirizzo IPv6 non valido."

#: ../src/ddns/providers.py:1630
#, fuzzy
msgid "Account has been suspended"
msgstr "L'utente è stato disabilitato"

#: ../src/ddns/providers.py:1633
#, fuzzy
msgid "Account has been revoked"
msgstr "L'utente è stato disabilitato"

#: ../src/ddns/system.py:56
#, python-format
msgid "Running on distribution: %s"
msgstr "In esecuzione sulla distribuzione: %s"

#: ../src/ddns/system.py:161
msgid "Request header:"
msgstr "Intestazione di richiesta:"

#. Log response header.
#: ../src/ddns/system.py:169 ../src/ddns/system.py:178
#, python-format
msgid "Response header (Status Code %s):"
msgstr "Testata della risposta (codice di stato %s)."

#: ../src/ddns/system.py:298
msgid "Falling back to check the IP address with help of a public server"
msgstr ""

#~ msgid "Invalid hostname specified."
#~ msgstr "Nome host specificato non valido."
