# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# isama <bart.formosus@gmail.com>, 2014
# Hans <dutchtux@gmail.com>, 2013
# Hans <dutchtux@gmail.com>, 2014
# Jacques Hylkema <j.hylkema@intronics.nl>, 2015
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-05-07 12:54+0100\n"
"PO-Revision-Date: 2015-02-03 06:18+0000\n"
"Last-Translator: Jacques Hylkema <j.hylkema@intronics.nl>\n"
"Language-Team: Dutch (http://www.transifex.com/projects/p/ipfire/language/"
"nl/)\n"
"Language: nl\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../src/ddns/__init__.py:63
msgid "Debugging mode enabled"
msgstr "Debugging modus is geactiveerd"

#: ../src/ddns/__init__.py:90
#, python-format
msgid "Loading configuration file %s"
msgstr "Inladen configuratiebestand %s"

#: ../src/ddns/__init__.py:156
msgid "Found no entries in the configuration file. Exiting."
msgstr "Geen items gevonden in het configuratiebestand. Gestopt."

#: ../src/ddns/__init__.py:167
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr "Dynamische DNS update voor %(hostname)s (%(provider)s) mislukt:"

#: ../src/ddns/__init__.py:174
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr ""
"Dynamische DNS update voor %(hostname)s (%(provider)s) gaf een onverwerkte "
"uitzondering:"

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr "Fout"

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr "Netwerkfout"

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr ""
"De server heeft het verzoek niet verwerkt omdat het account vermoedelijk is "
"misbruikt"

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr "Server authenticatie is mislukt"

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr "De server weigert updates van deze client"

#: ../src/ddns/errors.py:71
msgid "Invalid certificate"
msgstr ""

#: ../src/ddns/errors.py:79
msgid "The configuration file has errors"
msgstr "Het configuratiebestand bevat fouten"

#: ../src/ddns/errors.py:86
msgid "Connection refused"
msgstr "Verbinding geweigerd"

#: ../src/ddns/errors.py:93 ../src/ddns/system.py:240
msgid "Connection timeout"
msgstr "Verbinding timeout"

#: ../src/ddns/errors.py:101
msgid "The host could not be found in the configuration file"
msgstr "De host werd niet gevonden in het configuratiebestand"

#: ../src/ddns/errors.py:109
msgid "Internal server error"
msgstr "Interne serverfout"

#: ../src/ddns/errors.py:116
msgid "Network unreachable"
msgstr "Netwerk onbereikbaar"

#: ../src/ddns/errors.py:123
msgid "No route to host"
msgstr ""

#: ../src/ddns/errors.py:130
msgid "Not found"
msgstr "Niet gevonden"

#: ../src/ddns/errors.py:138
msgid "Request error"
msgstr "Opvraagfout"

#: ../src/ddns/errors.py:146
msgid "Could not resolve DNS entry"
msgstr "Kon de DNS ingang niet oplossen"

#: ../src/ddns/errors.py:154
msgid "SSL negotiation error"
msgstr ""

#: ../src/ddns/errors.py:161
msgid "Service unavailable"
msgstr "Dienst niet beschikbaaar"

#: ../src/ddns/errors.py:169
msgid "The update could not be performed"
msgstr "De update kon niet worden uitgevoerd"

#: ../src/ddns/providers.py:85
msgid "Provider is not properly configured"
msgstr "Provider is niet goed geconfigureerd"

#: ../src/ddns/providers.py:154
#, python-format
msgid "Updating %s forced"
msgstr "Bijwerken %s gereed"

#: ../src/ddns/providers.py:179
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr "Dynamische DNS update voor %(hostname)s (%(provider)s) geslaagd"

#: ../src/ddns/providers.py:203
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because of an IP "
"address change"
msgstr ""
"Een update voor %(hostname)s (%(provider)s) is uitgevoerd wegens een IP "
"adres wijziging"

#: ../src/ddns/providers.py:211
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because the holdoff "
"time has expired"
msgstr ""
"Een update voor %(hostname)s (%(provider)s) is uitgevoerd omdat de holdoff "
"tijd is verstreken"

#. Otherwise, we don't need to perform an update
#: ../src/ddns/providers.py:218
#, python-format
msgid "No update required for %(hostname)s (%(provider)s)"
msgstr "Geen update nodig voor %(hostname)s (%(provider)s)"

#: ../src/ddns/providers.py:237 ../src/ddns/providers.py:251
#, python-format
msgid "An update has not been performed because earlier updates failed for %s"
msgstr ""
"Een update is niet uitgevoerd doordat eerdere updates zijn mislukt voor %s"

#: ../src/ddns/providers.py:239
msgid "There will be no retries"
msgstr "Er  zal niet opnieuw worden geprobeerd"

#: ../src/ddns/providers.py:255
msgid "Last failure message:"
msgstr "Vorige foutmelding:"

#: ../src/ddns/providers.py:260
#, python-format
msgid "Further updates will be withheld until %s"
msgstr "Verdere updates worden terug gehouden tot %s"

#: ../src/ddns/providers.py:394 ../src/ddns/providers.py:668
#: ../src/ddns/providers.py:752 ../src/ddns/providers.py:1419
#: ../src/ddns/providers.py:1589
#, fuzzy
msgid "No valid FQDN was given"
msgstr "Geen geldige FQDN opgegeven."

#: ../src/ddns/providers.py:396 ../src/ddns/providers.py:670
#: ../src/ddns/providers.py:1636
#, fuzzy
msgid "Specified host does not exist"
msgstr "Opgegeven host bestaat niet."

#: ../src/ddns/providers.py:400 ../src/ddns/providers.py:674
#, fuzzy
msgid "DNS error encountered"
msgstr "DNS fout geconstateerd."

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:405 ../src/ddns/providers.py:586
#: ../src/ddns/providers.py:973 ../src/ddns/providers.py:1642
#, python-format
msgid "Server response: %s"
msgstr "Server antwoord: %s"

#: ../src/ddns/providers.py:540
msgid "Scriptlet:"
msgstr "Scriptlet:"

#: ../src/ddns/providers.py:577
msgid "Domain not found."
msgstr "Domein niet gevonden."

#: ../src/ddns/providers.py:676
#, fuzzy
msgid "Account disabled or locked"
msgstr "Account is uitgeschakeld."

#: ../src/ddns/providers.py:754 ../src/ddns/providers.py:801
#: ../src/ddns/providers.py:1682
msgid "Invalid hostname specified"
msgstr "Ongeldige hostnaam opgegeven"

#: ../src/ddns/providers.py:756
#, fuzzy
msgid "Hostname not marked as a dynamic host"
msgstr "Hostnaam is niet gemarkeerd als dynamische host."

#: ../src/ddns/providers.py:758 ../src/ddns/providers.py:810
#: ../src/ddns/providers.py:1093
#, fuzzy
msgid "Invalid IP address has been sent"
msgstr "Ongeldig IP adres is verzonden."

#: ../src/ddns/providers.py:798
#, fuzzy
msgid "No hostname specified"
msgstr "Geen hostnaam opgegeven."

#: ../src/ddns/providers.py:807
#, fuzzy
msgid "Account has been disabled"
msgstr "Account is uitgeschakeld."

#: ../src/ddns/providers.py:813
#, fuzzy
msgid "Too many failed requests"
msgstr "Teveel mislukte pogingen."

#: ../src/ddns/providers.py:908
msgid "Dynamic DNS is not turned on for this domain"
msgstr ""

#: ../src/ddns/providers.py:911
#, fuzzy
msgid "Invalid data has been sent"
msgstr "Ongeldig IP adres is verzonden."

#: ../src/ddns/providers.py:914 ../src/ddns/providers.py:968
#: ../src/ddns/providers.py:1591
#, fuzzy
msgid "Too frequent update requests have been sent"
msgstr "Er zijn teveel update verzoeken verstuurd."

#: ../src/ddns/providers.py:964
#, fuzzy
msgid "Malformed request has been sent"
msgstr "Er is een ongeldig verzoek verstuurd."

#: ../src/ddns/providers.py:1014 ../src/ddns/providers.py:1241
#, fuzzy
msgid "Domain not found"
msgstr "Domein niet gevonden."

#: ../src/ddns/providers.py:1049
msgid "An invalid IP address was submitted"
msgstr "Een ongeldig IP adres was opgegeven"

#: ../src/ddns/providers.py:1243
#, fuzzy
msgid "Domain not active"
msgstr "Domein niet actief."

#: ../src/ddns/providers.py:1393
#, fuzzy
msgid "No Auth details specified"
msgstr "Geen authenticatie details opgegeven."

#: ../src/ddns/providers.py:1415
#, fuzzy
msgid "Invalid IPv4 address has been sent"
msgstr "Ongeldig IPv4 adres is verstuurd."

#: ../src/ddns/providers.py:1417
#, fuzzy
msgid "Invalid IPv6 address has been sent"
msgstr "Ongeldig IPv6 adres is verstuurd."

#: ../src/ddns/providers.py:1630
#, fuzzy
msgid "Account has been suspended"
msgstr "Account is uitgeschakeld."

#: ../src/ddns/providers.py:1633
#, fuzzy
msgid "Account has been revoked"
msgstr "Account is uitgeschakeld."

#: ../src/ddns/system.py:56
#, python-format
msgid "Running on distribution: %s"
msgstr "Draait op distributie: %s"

#: ../src/ddns/system.py:161
msgid "Request header:"
msgstr "Aanvraag header:"

#. Log response header.
#: ../src/ddns/system.py:169 ../src/ddns/system.py:178
#, python-format
msgid "Response header (Status Code %s):"
msgstr "Antwoord header (statuscode %s):"

#: ../src/ddns/system.py:298
msgid "Falling back to check the IP address with help of a public server"
msgstr ""

#~ msgid "Invalid hostname specified."
#~ msgstr "Ongeldige hostnaam opgegeven."
