# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# André Felipe Morro <andre@andremorro.com>, 2012
# André Felipe Morro <andre@andremorro.com>, 2014
# Evertton de Lima <e.everttonlima@gmail.com>, 2015
# Flávio Veras <flaviove@gmail.com>, 2014
# Leandro Luquetti Basilio da Silva <leandroluquetti@gmail.com>, 2014
# Moisés Bites Borges de Castro <moisesbites@gmail.com>, 2015
# Rafael Lehnhart <lehnhart@gmail.com>, 2015
# Rafael Tavares <rafael@ibinetwork.com.br>, 2015
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-05-07 12:54+0100\n"
"PO-Revision-Date: 2015-10-06 12:53+0000\n"
"Last-Translator: Rafael Lehnhart <lehnhart@gmail.com>\n"
"Language-Team: Portuguese (Brazil) (http://www.transifex.com/mstremer/ipfire/"
"language/pt_BR/)\n"
"Language: pt_BR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: ../src/ddns/__init__.py:63
msgid "Debugging mode enabled"
msgstr "Modo de depuração habilitado"

#: ../src/ddns/__init__.py:90
#, python-format
msgid "Loading configuration file %s"
msgstr "Carregando arquivo de configuração %s"

#: ../src/ddns/__init__.py:156
msgid "Found no entries in the configuration file. Exiting."
msgstr "Não foram encontradas entradas no arquivo de configuração. Saindo."

#: ../src/ddns/__init__.py:167
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr "Atualização de DNS Dinâmico para %(hostname)s (%(provider)s) falhou:"

#: ../src/ddns/__init__.py:174
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr ""
"Atualização de DNS Dinâmico para %(hostname)s (%(provider)s) teve uma "
"exceção não tratada:"

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr "Erro"

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr "Erro de rede"

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr ""
"O servidor negou o processamento do pedido, por suspeita de abuso na conta"

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr "Autenticação contra o servidor falhou"

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr "O servidor nega quaisquer atualizações deste cliente"

#: ../src/ddns/errors.py:71
msgid "Invalid certificate"
msgstr ""

#: ../src/ddns/errors.py:79
msgid "The configuration file has errors"
msgstr "O arquivo de configuração tem erros"

#: ../src/ddns/errors.py:86
msgid "Connection refused"
msgstr "Conexão recusada"

#: ../src/ddns/errors.py:93 ../src/ddns/system.py:240
msgid "Connection timeout"
msgstr "Tempo limite de conexão"

#: ../src/ddns/errors.py:101
msgid "The host could not be found in the configuration file"
msgstr "O host não pôde ser encontrado no arquivo de configuração"

#: ../src/ddns/errors.py:109
msgid "Internal server error"
msgstr "Erro Interno do Servidor"

#: ../src/ddns/errors.py:116
msgid "Network unreachable"
msgstr "Rede inacessível"

#: ../src/ddns/errors.py:123
msgid "No route to host"
msgstr ""

#: ../src/ddns/errors.py:130
msgid "Not found"
msgstr "Não encontrado"

#: ../src/ddns/errors.py:138
msgid "Request error"
msgstr "Erro de requisição"

#: ../src/ddns/errors.py:146
msgid "Could not resolve DNS entry"
msgstr "Não foi possível resolver a entrada DNS"

#: ../src/ddns/errors.py:154
msgid "SSL negotiation error"
msgstr ""

#: ../src/ddns/errors.py:161
msgid "Service unavailable"
msgstr "Serviço indisponível"

#: ../src/ddns/errors.py:169
msgid "The update could not be performed"
msgstr "A atualizalçao não pode ser realizada"

#: ../src/ddns/providers.py:85
msgid "Provider is not properly configured"
msgstr "Provedor não está configurado corretamente"

#: ../src/ddns/providers.py:154
#, python-format
msgid "Updating %s forced"
msgstr "Atualição de %s forçada"

#: ../src/ddns/providers.py:179
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr ""
"Atualização de DNS Dinâmico para %(hostname)s (%(provider)s) bem sucedida"

#: ../src/ddns/providers.py:203
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because of an IP "
"address change"
msgstr ""
"Uma atualização para %(hostname)s (%(provider)s) é realizada por causa da "
"mudança de endereço IP"

#: ../src/ddns/providers.py:211
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because the holdoff "
"time has expired"
msgstr ""
"Uma atualização para %(hostname)s (%(provider)s) é realizada porque o tempo "
"de interrupção expirou"

#. Otherwise, we don't need to perform an update
#: ../src/ddns/providers.py:218
#, python-format
msgid "No update required for %(hostname)s (%(provider)s)"
msgstr "Nenhuma atualização requerida para %(hostname)s (%(provider)s)"

#: ../src/ddns/providers.py:237 ../src/ddns/providers.py:251
#, python-format
msgid "An update has not been performed because earlier updates failed for %s"
msgstr ""
"Uma atualização não foi executada porque as anteriores falharam para %s"

#: ../src/ddns/providers.py:239
msgid "There will be no retries"
msgstr "Não haveram novas tentativas"

#: ../src/ddns/providers.py:255
msgid "Last failure message:"
msgstr "Última mensagem de falha:"

#: ../src/ddns/providers.py:260
#, python-format
msgid "Further updates will be withheld until %s"
msgstr "Novas atualizações serão retidas até que %s"

#: ../src/ddns/providers.py:394 ../src/ddns/providers.py:668
#: ../src/ddns/providers.py:752 ../src/ddns/providers.py:1419
#: ../src/ddns/providers.py:1589
#, fuzzy
msgid "No valid FQDN was given"
msgstr "Não foi dado um FQDN válido."

#: ../src/ddns/providers.py:396 ../src/ddns/providers.py:670
#: ../src/ddns/providers.py:1636
#, fuzzy
msgid "Specified host does not exist"
msgstr "Host especificado não existe."

#: ../src/ddns/providers.py:400 ../src/ddns/providers.py:674
#, fuzzy
msgid "DNS error encountered"
msgstr "Encontrado erro de DNS."

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:405 ../src/ddns/providers.py:586
#: ../src/ddns/providers.py:973 ../src/ddns/providers.py:1642
#, python-format
msgid "Server response: %s"
msgstr "Resposta do servidor: %s"

#: ../src/ddns/providers.py:540
msgid "Scriptlet:"
msgstr "Scriptlet:"

#: ../src/ddns/providers.py:577
msgid "Domain not found."
msgstr "Domínio não encontrado."

#: ../src/ddns/providers.py:676
#, fuzzy
msgid "Account disabled or locked"
msgstr "A conta foi desabilitada."

#: ../src/ddns/providers.py:754 ../src/ddns/providers.py:801
#: ../src/ddns/providers.py:1682
msgid "Invalid hostname specified"
msgstr "Hostname especificado inválido"

#: ../src/ddns/providers.py:756
#, fuzzy
msgid "Hostname not marked as a dynamic host"
msgstr "Hostname não marcado como host dinâmico."

#: ../src/ddns/providers.py:758 ../src/ddns/providers.py:810
#: ../src/ddns/providers.py:1093
#, fuzzy
msgid "Invalid IP address has been sent"
msgstr "Endereço IP inválido foi enviado."

#: ../src/ddns/providers.py:798
#, fuzzy
msgid "No hostname specified"
msgstr "Nenhum hostname foi espacificado."

#: ../src/ddns/providers.py:807
#, fuzzy
msgid "Account has been disabled"
msgstr "A conta foi desabilitada."

#: ../src/ddns/providers.py:813
#, fuzzy
msgid "Too many failed requests"
msgstr "Muitas requisições falhas."

#: ../src/ddns/providers.py:908
msgid "Dynamic DNS is not turned on for this domain"
msgstr ""

#: ../src/ddns/providers.py:911
#, fuzzy
msgid "Invalid data has been sent"
msgstr "Endereço IP inválido foi enviado."

#: ../src/ddns/providers.py:914 ../src/ddns/providers.py:968
#: ../src/ddns/providers.py:1591
#, fuzzy
msgid "Too frequent update requests have been sent"
msgstr "Solicitações de atualização tem sido enviadas muito frequentemente."

#: ../src/ddns/providers.py:964
#, fuzzy
msgid "Malformed request has been sent"
msgstr "Solicitação mal concebida foi enviada."

#: ../src/ddns/providers.py:1014 ../src/ddns/providers.py:1241
#, fuzzy
msgid "Domain not found"
msgstr "Domínio não encontrado."

#: ../src/ddns/providers.py:1049
msgid "An invalid IP address was submitted"
msgstr "Um endereço IP inválido foi enviado"

#: ../src/ddns/providers.py:1243
#, fuzzy
msgid "Domain not active"
msgstr "Domínio não está ativo."

#: ../src/ddns/providers.py:1393
#, fuzzy
msgid "No Auth details specified"
msgstr "Nenhum detalhe de autenticação especificado."

#: ../src/ddns/providers.py:1415
#, fuzzy
msgid "Invalid IPv4 address has been sent"
msgstr "Endereço IPv4 enviado é inválido."

#: ../src/ddns/providers.py:1417
#, fuzzy
msgid "Invalid IPv6 address has been sent"
msgstr "Endereço IPv6 enviado é inválido."

#: ../src/ddns/providers.py:1630
#, fuzzy
msgid "Account has been suspended"
msgstr "A conta foi desabilitada."

#: ../src/ddns/providers.py:1633
#, fuzzy
msgid "Account has been revoked"
msgstr "A conta foi desabilitada."

#: ../src/ddns/system.py:56
#, python-format
msgid "Running on distribution: %s"
msgstr "Rodando na distribuição: %s"

#: ../src/ddns/system.py:161
msgid "Request header:"
msgstr "Header solicitada:"

#. Log response header.
#: ../src/ddns/system.py:169 ../src/ddns/system.py:178
#, python-format
msgid "Response header (Status Code %s):"
msgstr "Cabeçalho de resposta (código de status %s):"

#: ../src/ddns/system.py:298
msgid "Falling back to check the IP address with help of a public server"
msgstr ""

#~ msgid "Invalid hostname specified."
#~ msgstr "Hostname especificado inválido."
