# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Alexander Savchenko, 2014
# Andrei Skipin <skian2007@yandex.ru>, 2014
# ellviss <kpe1501@gmail.com>, 2015
# bubnov_pi <ipfire@bubnov.su>, 2014
# Вальчишин Андрій Олегович <v.andrey@i.ua>, 2012
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-05-07 12:54+0100\n"
"PO-Revision-Date: 2015-02-17 19:26+0000\n"
"Last-Translator: ellviss <kpe1501@gmail.com>\n"
"Language-Team: Russian (http://www.transifex.com/projects/p/ipfire/language/"
"ru/)\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

#: ../src/ddns/__init__.py:63
msgid "Debugging mode enabled"
msgstr "Включён режим отладки"

#: ../src/ddns/__init__.py:90
#, python-format
msgid "Loading configuration file %s"
msgstr "Загружается файл конфигурации %s"

#: ../src/ddns/__init__.py:156
msgid "Found no entries in the configuration file. Exiting."
msgstr "Не найдено записей в конфигурационном файле. Выход."

#: ../src/ddns/__init__.py:167
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr "Ошибка обновления Dynamic DNS для %(hostname)s (%(provider)s):"

#: ../src/ddns/__init__.py:174
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr ""
"Обновление Dynamic DNS для %(hostname)s (%(provider)s) вызвало "
"необработанное исключение:"

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr "Ошибка"

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr "Сетевая ошибка"

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr ""
"Сервер отклонил обработку запроса из-за подозрения в компрометации аккаунта."

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr "Неудачная авторизация на сервере"

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr "Сервер отклоняет любые обновления от этого клиента"

#: ../src/ddns/errors.py:71
msgid "Invalid certificate"
msgstr ""

#: ../src/ddns/errors.py:79
msgid "The configuration file has errors"
msgstr "Конфигурационный файл содержит ошибки"

#: ../src/ddns/errors.py:86
msgid "Connection refused"
msgstr "Соединение отклонено"

#: ../src/ddns/errors.py:93 ../src/ddns/system.py:240
msgid "Connection timeout"
msgstr "Тайм-аут подключения"

#: ../src/ddns/errors.py:101
msgid "The host could not be found in the configuration file"
msgstr "Хост не найден в файле конфигурации"

#: ../src/ddns/errors.py:109
msgid "Internal server error"
msgstr "Внутренняя ошибка сервера"

#: ../src/ddns/errors.py:116
msgid "Network unreachable"
msgstr "Сеть недоступна"

#: ../src/ddns/errors.py:123
msgid "No route to host"
msgstr ""

#: ../src/ddns/errors.py:130
msgid "Not found"
msgstr "Не найдено"

#: ../src/ddns/errors.py:138
msgid "Request error"
msgstr "Ошибка запроса"

#: ../src/ddns/errors.py:146
msgid "Could not resolve DNS entry"
msgstr "Невозможно разрешить запись DNS"

#: ../src/ddns/errors.py:154
msgid "SSL negotiation error"
msgstr ""

#: ../src/ddns/errors.py:161
msgid "Service unavailable"
msgstr "Сервис недоступен"

#: ../src/ddns/errors.py:169
msgid "The update could not be performed"
msgstr "Обновление не может быть выполнено"

#: ../src/ddns/providers.py:85
msgid "Provider is not properly configured"
msgstr "Провайдер не настроен"

#: ../src/ddns/providers.py:154
#, python-format
msgid "Updating %s forced"
msgstr "Принудительное обновление %s"

#: ../src/ddns/providers.py:179
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr ""
"Обновление Dynamic DNS для %(hostname)s (%(provider)s) выполнено успешно."

#: ../src/ddns/providers.py:203
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because of an IP "
"address change"
msgstr ""

#: ../src/ddns/providers.py:211
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because the holdoff "
"time has expired"
msgstr ""

#. Otherwise, we don't need to perform an update
#: ../src/ddns/providers.py:218
#, python-format
msgid "No update required for %(hostname)s (%(provider)s)"
msgstr ""

#: ../src/ddns/providers.py:237 ../src/ddns/providers.py:251
#, python-format
msgid "An update has not been performed because earlier updates failed for %s"
msgstr ""

#: ../src/ddns/providers.py:239
msgid "There will be no retries"
msgstr ""

#: ../src/ddns/providers.py:255
msgid "Last failure message:"
msgstr "Последнее сообщение об ошибке"

#: ../src/ddns/providers.py:260
#, python-format
msgid "Further updates will be withheld until %s"
msgstr ""

#: ../src/ddns/providers.py:394 ../src/ddns/providers.py:668
#: ../src/ddns/providers.py:752 ../src/ddns/providers.py:1419
#: ../src/ddns/providers.py:1589
#, fuzzy
msgid "No valid FQDN was given"
msgstr "Не дано верного FQDN"

#: ../src/ddns/providers.py:396 ../src/ddns/providers.py:670
#: ../src/ddns/providers.py:1636
#, fuzzy
msgid "Specified host does not exist"
msgstr "Указанный узел не существует."

#: ../src/ddns/providers.py:400 ../src/ddns/providers.py:674
#, fuzzy
msgid "DNS error encountered"
msgstr "Произошла ошибка DNS"

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:405 ../src/ddns/providers.py:586
#: ../src/ddns/providers.py:973 ../src/ddns/providers.py:1642
#, python-format
msgid "Server response: %s"
msgstr "Ответ сервера: %s"

#: ../src/ddns/providers.py:540
msgid "Scriptlet:"
msgstr ""

#: ../src/ddns/providers.py:577
msgid "Domain not found."
msgstr "Домен не найден."

#: ../src/ddns/providers.py:676
#, fuzzy
msgid "Account disabled or locked"
msgstr "Аккаунт отключен."

#: ../src/ddns/providers.py:754 ../src/ddns/providers.py:801
#: ../src/ddns/providers.py:1682
msgid "Invalid hostname specified"
msgstr "Указано неверное имя узла."

#: ../src/ddns/providers.py:756
#, fuzzy
msgid "Hostname not marked as a dynamic host"
msgstr "Узел не помечен как динамический."

#: ../src/ddns/providers.py:758 ../src/ddns/providers.py:810
#: ../src/ddns/providers.py:1093
#, fuzzy
msgid "Invalid IP address has been sent"
msgstr "Отправлен некорректный IP-адрес."

#: ../src/ddns/providers.py:798
#, fuzzy
msgid "No hostname specified"
msgstr "Не указано имя узла."

#: ../src/ddns/providers.py:807
#, fuzzy
msgid "Account has been disabled"
msgstr "Аккаунт отключен."

#: ../src/ddns/providers.py:813
#, fuzzy
msgid "Too many failed requests"
msgstr "Слишком много неудачных запросов."

#: ../src/ddns/providers.py:908
msgid "Dynamic DNS is not turned on for this domain"
msgstr ""

#: ../src/ddns/providers.py:911
#, fuzzy
msgid "Invalid data has been sent"
msgstr "Отправлен некорректный IP-адрес."

#: ../src/ddns/providers.py:914 ../src/ddns/providers.py:968
#: ../src/ddns/providers.py:1591
msgid "Too frequent update requests have been sent"
msgstr ""

#: ../src/ddns/providers.py:964
#, fuzzy
msgid "Malformed request has been sent"
msgstr "Отправлен некорректный IP-адрес."

#: ../src/ddns/providers.py:1014 ../src/ddns/providers.py:1241
#, fuzzy
msgid "Domain not found"
msgstr "Домен не найден."

#: ../src/ddns/providers.py:1049
msgid "An invalid IP address was submitted"
msgstr ""

#: ../src/ddns/providers.py:1243
#, fuzzy
msgid "Domain not active"
msgstr "Домен не активен."

#: ../src/ddns/providers.py:1393
#, fuzzy
msgid "No Auth details specified"
msgstr "Не указаны детали авторизации."

#: ../src/ddns/providers.py:1415
#, fuzzy
msgid "Invalid IPv4 address has been sent"
msgstr "Отправлен некорректный адрес IPv4."

#: ../src/ddns/providers.py:1417
#, fuzzy
msgid "Invalid IPv6 address has been sent"
msgstr "Отправлен некорректный адрес IPv6."

#: ../src/ddns/providers.py:1630
#, fuzzy
msgid "Account has been suspended"
msgstr "Аккаунт отключен."

#: ../src/ddns/providers.py:1633
#, fuzzy
msgid "Account has been revoked"
msgstr "Аккаунт отключен."

#: ../src/ddns/system.py:56
#, python-format
msgid "Running on distribution: %s"
msgstr "Выполняется распространение: %s"

#: ../src/ddns/system.py:161
msgid "Request header:"
msgstr "Заголовок запроса:"

#. Log response header.
#: ../src/ddns/system.py:169 ../src/ddns/system.py:178
#, python-format
msgid "Response header (Status Code %s):"
msgstr "Заголовок ответа (Статус %s):"

#: ../src/ddns/system.py:298
msgid "Falling back to check the IP address with help of a public server"
msgstr ""

#~ msgid "Invalid hostname specified."
#~ msgstr "Указано неверное имя узла."
