# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# softballs <andreas@meriq.se>, 2014
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-08-04 14:54+0000\n"
"PO-Revision-Date: 2014-06-23 08:45+0000\n"
"Last-Translator: Michael Tremer <michael.tremer@ipfire.org>\n"
"Language-Team: Swedish (http://www.transifex.com/projects/p/ipfire/language/"
"sv/)\n"
"Language: sv\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../src/ddns/__init__.py:62
msgid "Debugging mode enabled"
msgstr ""

#: ../src/ddns/__init__.py:86
#, python-format
msgid "Loading configuration file %s"
msgstr ""

#: ../src/ddns/__init__.py:146
msgid "Found no entries in the configuration file. Exiting."
msgstr "Hittade inte några inlägg i konfigurations filen. Avslutar."

#: ../src/ddns/__init__.py:157
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr ""

#: ../src/ddns/__init__.py:164
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr ""

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr ""

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr ""

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr ""

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr ""

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr ""

#: ../src/ddns/errors.py:72
msgid "The configuration file has errors"
msgstr ""

#: ../src/ddns/errors.py:79
msgid "Connection refused"
msgstr ""

#: ../src/ddns/errors.py:86 ../src/ddns/system.py:212
msgid "Connection timeout"
msgstr ""

#: ../src/ddns/errors.py:94
msgid "The host could not be found in the configuration file"
msgstr ""

#: ../src/ddns/errors.py:102
msgid "Internal server error"
msgstr ""

#: ../src/ddns/errors.py:109
msgid "Network unreachable"
msgstr ""

#: ../src/ddns/errors.py:117
msgid "Request error"
msgstr ""

#: ../src/ddns/errors.py:125
msgid "Could not resolve DNS entry"
msgstr ""

#: ../src/ddns/errors.py:132
msgid "Service unavailable"
msgstr ""

#: ../src/ddns/errors.py:140
msgid "The update could not be performed"
msgstr ""

#: ../src/ddns/providers.py:71
msgid "Provider is not properly configured"
msgstr ""

#: ../src/ddns/providers.py:128
#, python-format
msgid "Updating %s forced"
msgstr ""

#: ../src/ddns/providers.py:132
#, python-format
msgid "The dynamic host %(hostname)s (%(provider)s) is already up to date"
msgstr ""

#: ../src/ddns/providers.py:139
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr ""

#: ../src/ddns/providers.py:220 ../src/ddns/providers.py:424
#: ../src/ddns/providers.py:929 ../src/ddns/providers.py:1077
msgid "No valid FQDN was given."
msgstr ""

#: ../src/ddns/providers.py:222
msgid "Specified host does not exist."
msgstr ""

#: ../src/ddns/providers.py:226
msgid "DNS error encountered."
msgstr ""

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:229
#, python-format
msgid "Server response: %s"
msgstr ""

#: ../src/ddns/providers.py:345
msgid "Scriptlet:"
msgstr ""

#: ../src/ddns/providers.py:426 ../src/ddns/providers.py:472
msgid "Invalid hostname specified."
msgstr ""

#: ../src/ddns/providers.py:428
msgid "Hostname not marked as a dynamic host."
msgstr ""

#: ../src/ddns/providers.py:430 ../src/ddns/providers.py:481
#: ../src/ddns/providers.py:658
msgid "Invalid IP address has been sent."
msgstr ""

#: ../src/ddns/providers.py:469
msgid "No hostname specified."
msgstr ""

#: ../src/ddns/providers.py:478
msgid "Account has been disabled."
msgstr ""

#: ../src/ddns/providers.py:484
msgid "Too many failed requests."
msgstr ""

#: ../src/ddns/providers.py:575 ../src/ddns/providers.py:746
msgid "Domain not found."
msgstr ""

#: ../src/ddns/providers.py:609
msgid "An invalid IP address was submitted"
msgstr ""

#: ../src/ddns/providers.py:748
msgid "Domain not active."
msgstr ""

#: ../src/ddns/providers.py:809
msgid "Invalid protocol has been given"
msgstr ""

#: ../src/ddns/providers.py:903
msgid "No Auth details specified."
msgstr ""

#: ../src/ddns/providers.py:925
msgid "Invalid IPv4 address has been sent."
msgstr ""

#: ../src/ddns/providers.py:927
msgid "Invalid IPv6 address has been sent."
msgstr ""

#: ../src/ddns/system.py:55
#, python-format
msgid "Running on distribution: %s"
msgstr ""

#: ../src/ddns/system.py:153
msgid "Request header:"
msgstr ""

#. Log response header.
#: ../src/ddns/system.py:161 ../src/ddns/system.py:170
#, python-format
msgid "Response header (Status Code %s):"
msgstr ""
